name: build

on:
  push:
    branches: master

jobs:

  build:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout nix-darwin
      uses: actions/checkout@v2
      with:
        repository: LnL7/nix-darwin
        path: nix-darwin

    - name: Install Nix
      uses: cachix/install-nix-action@v10

    - name: Build installer
      run: ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nix-darwin-installer
        path: nix-darwin-installer.tar.xz

  test:
    runs-on: macos-latest
    needs: build
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nix-darwin-installer

    - name: Run installer
      run: |
        tar -xf nix-darwin-installer.tar.xz
        ./nix-darwin-installer/install.sh < /dev/null

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nix-darwin-installer

    - name: Push gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -xeuo pipefail
        REPO="$PWD"

        git config --global user.name "GitHub Actions"
        git config --global user.email "bot@stephank.nl"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

        git branch -D gh-pages || true
        git worktree add --detach ../site-build
        cd ../site-build
        git checkout --orphan gh-pages
        git reset --hard

        cp -R "$REPO/support/site"/* ./
        mv "$REPO/nix-darwin-installer.tar.xz" ./
        git add .
        git commit -m "Automated build"
        git push -f github gh-pages
