name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: '**'
  schedule:
  - cron: '49 1 * * *'

jobs:

  build:
    runs-on: macos-10.15
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      run: |
        mkdir -p "$HOME/.nixpkgs"
        cp support/base-system-config.nix "$HOME/.nixpkgs/darwin-configuration.nix"

        /bin/bash -c "$(curl -fsSL https://stephank.github.io/nix-darwin-installer/install.sh)"

        echo "/run/current-system/sw/bin" >> $GITHUB_PATH
        echo "NIX_PATH=$HOME/.nix-defexpr/channels" >> $GITHUB_ENV

    - name: Build installer
      run: ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nix-darwin-installer
        path: nix-darwin-installer.tar.xz

  test:
    runs-on: macos-10.15
    needs: build
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nix-darwin-installer

    - name: Run installer
      run: |
        mkdir -p "$HOME/.nixpkgs"
        cp support/base-system-config.nix "$HOME/.nixpkgs/darwin-configuration.nix"

        tar -xf nix-darwin-installer.tar.xz
        ./nix-darwin-installer/install.sh < /dev/null

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nix-darwin-installer

    - name: Push gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -xeuo pipefail
        REPO="$PWD"

        git config --global user.name "GitHub Actions"
        git config --global user.email "bot@stephank.nl"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

        git branch -D gh-pages || true
        git worktree add --detach ../site-build
        cd ../site-build
        git checkout --orphan gh-pages
        git reset --hard

        rsync -r "$REPO/support/site/" ./
        mv "$REPO/nix-darwin-installer.tar.xz" ./
        cp "$REPO/README.md" ./index.md
        echo -e "\nLast update: $(date -u "+%a, %d %b %Y %T UTC")" >> ./index.md
        git add .
        git commit -m "Automated build"
        git push -f github gh-pages
